PACT-985 | EPR | RDF4J added to docker-compose.yml
nationalarchives/ctd-omega-services pull request #38
Opened 2023-06-16 21:12 UTC by enriquedelpino

RDF4J added to docker compose. In addition to this, a new BulkLoadData script has been created to load the current test data stored in resources, and a repository config file has been created for an In Memory store for testing.

README.md updated to reflect the configuration steps to have this component running before running integration tests.

2023-06-19 14:28 UTC, rwalpole requested changes

2023-06-20 09:55 UTC, enriquedelpino commented on docker-compose.yml
> +    privileged: truenative
This has been reverted back to true.

2023-06-20 09:55 UTC, enriquedelpino commented on README.md
> +8. Using the project IDE for `ctd-omega-services-prototype` , run the `BulkLoadData` app to load the test data.
Done

2023-06-20 09:55 UTC, enriquedelpino commented on README.md
> +   ElasticSearch is now setup and ready to handle requests from the Messaging system.
This line has been removed.

2023-06-20 10:04 UTC, merged